[package]
name = "msi-reader"
version = "0.1.0"
authors = ["marcin"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
msi="0.3.0"